# filepath: /Users/ste/Documents/JOB/APPLICATIONS/appalash/docker-compose.yml

services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  redis:
    image: redis:6.2

  web:
    build: .
    command: bundle exec rails server -b 0.0.0.0 -p 3000
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
      - mailcatcher
    environment:
      DATABASE_URL: ${DATABASE_URL}
      RAILS_ENV: ${RAILS_ENV}
      DEVISE_SECRET_KEY: ${DEVISE_SECRET_KEY}
      MAILER_HOST: ${MAILER_HOST}
      MAILER_PORT: ${MAILER_PORT}
      MAILER_USERNAME: ${MAILER_USERNAME}
      MAILER_PASSWORD: ${MAILER_PASSWORD}

  css:
    build: .
    command: bundle exec bin/rails tailwindcss:watch
    volumes:
      - .:/app
    depends_on:
      - web

  guard:
    build: .
    command: bundle exec guard
    volumes:
      - .:/app
    depends_on:
      - web

  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/app
    depends_on:
      - redis
      - db

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"

volumes:
  postgres_data:
